### ISSUE TITLE
Webpack code splitting

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#33] opened 2017-08-30 09:48 UTC
So far everything is in one big-ass js file. Vue seems to make it rather easy in combination with Webpack to split components into various js files and load them on demand. Especially views and dialogs should be separated into different files IMHO, but we could also do that for certain plugins or fields to minimize the main bundle.

**Comment by nocksock** [comment] 2017-10-29 20:01
Isn't this a duplicate of #201?

**Comment by distantnative** [comment] 2017-10-29 20:03
Indeed

**Closed** 2017-10-29 20:03 UTC
Labels: type: enhancement
